Prevent over-aggressive takeover when we see an UP event by checking the other hands.  If there are one explicitly "BACKUP" then we are preempting too early, reduce advskew to 240 (least preferred) and wait for another event (if that "BACKUP" wents "MASTER" then we will take over).
Ticket: #3476

diff --git a/src/freenas/etc/rc.d/ix-devd b/src/freenas/etc/rc.d/ix-devd
--- a/src/freenas/etc/rc.d/ix-devd
+++ b/src/freenas/etc/rc.d/ix-devd
@@ -89,6 +89,14 @@ if [ \${EVENT} = "LINK_UP" ]; then
 	exit 0
     fi
 
+    BACKUPS=\$(ifconfig -l | tr \  \\\\n | grep ^carp | grep -v '^carp[12]$' | xargs -n 1 ifconfig | grep "carp: BACKUP" | wc -l )
+    if [ \${BACKUPS} -gt 0 ]; then
+	ifconfig \${SUBSYSTEM} advskew 240
+	echo "Ignoring UP state on \${SUBSYSTEM} because we still have interfaces that are BACKUP." | logger
+	echo "\$(date), \$(hostname), \${SUBSYSTEM} assumed master while other interfaces are still in slave mode." | mail -s "Failover WARNING" root
+	exit 1
+    fi
+
     pkill -f fenced
 
     echo "set block-policy drop" > /etc/pf.conf.block
