Final failover changes to support manually kicking a head into active state

diff --git a/src/freenas/etc/rc.d/ix-devd b/src/freenas/etc/rc.d/ix-devd
--- a/src/freenas/etc/rc.d/ix-devd
+++ b/src/freenas/etc/rc.d/ix-devd
@@ -44,6 +44,13 @@ fi
 
 touch -t \`date -v -1M +%Y%m%d%H%M.%S\` /tmp/heartbeat_barrier
 
+# Has the user indicated we should take over?
+if  [ -f /tmp/failover_override ] ; then
+    USER_OVERRIDE=1
+else
+    USER_OVERRIDE=0
+fi
+
 # Do we have a force seal?
 HAVE_FORCESEAL=\`find /tmp/force_seal -mnewer /tmp/heartbeat_barrier | wc -l\`
 
@@ -54,7 +61,9 @@ if [ \${EVENT} = "LINK_UP" ]; then
     WASCONNECTED=\`find /tmp/heartbeat_state -mnewer /tmp/heartbeat_barrier | wc -l\`
 
     # If we can still ping the peer, quit immediately
-    ping -qc 1 -t 1 ${peerip} && exit
+    if [ \${USER_OVERRIDE} -eq 0 ] ; then
+        ping -qc 1 -t 1 ${peerip} && exit
+    fi
 
     if [ \${HAVE_FORCESEAL} -eq 1 ]; then
 	WASCONNECTED=1
@@ -62,67 +71,71 @@ if [ \${EVENT} = "LINK_UP" ]; then
 
     # Continously pool carp1 and carp2 until we have 5 seconds worth of
     # approval signal.
-    TIMER1=0
-    TIMER2=0
+    if [ \${USER_OVERRIDE} -eq 0 ] ; then
+        TIMER1=0
+        TIMER2=0
 
-    while [ \${TIMER2} -lt 60 ]; do
-	TIMER2=\$((TIMER2 + 1))
+        while [ \${TIMER2} -lt 60 ]; do
+	    TIMER2=\$((TIMER2 + 1))
 
-	STATUS0=\`ifconfig \${SUBSYSTEM} | grep "carp:" | awk '{print \$2}'\`
-	STATUS1=\`(ifconfig carp1 | grep carp: | awk '{print \$2;}' ; ifconfig carp2 | grep carp: | awk '{print \$2;}')| grep MASTER | wc -l\`
-	STATUS2=\`(ifconfig carp1 | grep carp: | awk '{print \$2;}' ; ifconfig carp2 | grep carp: | awk '{print \$2;}')| grep BACKUP | wc -l\`
+	    STATUS0=\`ifconfig \${SUBSYSTEM} | grep "carp:" | awk '{print \$2}'\`
+	    STATUS1=\`(ifconfig carp1 | grep carp: | awk '{print \$2;}' ; ifconfig carp2 | grep carp: | awk '{print \$2;}')| grep MASTER | wc -l\`
+	    STATUS2=\`(ifconfig carp1 | grep carp: | awk '{print \$2;}' ; ifconfig carp2 | grep carp: | awk '{print \$2;}')| grep BACKUP | wc -l\`
 
-	echo \${STATUS0}:\${STATUS1}:\${STATUS2} t1=\${TIMER1} t2=\${TIMER2} | logger
+	    echo \${STATUS0}:\${STATUS1}:\${STATUS2} t1=\${TIMER1} t2=\${TIMER2} | logger
 
-	if [ \$STATUS0 != "MASTER" ]; then
-	    echo "Promoted then demoted, quitting." | logger
-	    # Just in case.  Demote ourselves.
-	    ifconfig \${SUBSYSTEM} advskew 202
-	    exit
-	fi
-
-	# This catches the case where one head is powered off but the
-	# ethernet link shows as active due to the motherboard receiving
-	# power.  The link speed in this case will be 10baseT and the status
-	# will be active.  This test is not perfect because the physical
-	# failover interface is not explicitely defined, so it would be possible
-	# for another interface in the box to be in this state and "fake out"
-	# the script.
-	if [ \${STATUS1} -eq 2 -a \${STATUS2} -eq 0 ] ; then
-	    if [ \$WASCONNECTED -ne 1 ]; then
-		for i in \`ifconfig -lu\`
-		do
-		    ifconfig \$i | grep 10baseT/UTP
-		    if [ \$? -eq 0 ] ; then
-			LINKSTATUS=\`ifconfig \$i | grep status | awk '{print \$2}'\`
-			if [ \${LINKSTATUS} == "active" ] ; then
-			    WASCONNECTED=1
-			fi
-		    fi
-	        done
+	    if [ \$STATUS0 != "MASTER" ]; then
+	        echo "Promoted then demoted, quitting." | logger
+	        # Just in case.  Demote ourselves.
+	        ifconfig \${SUBSYSTEM} advskew 202
+	        exit
 	    fi
-	    TIMER1=\$((TIMER1 + 1))
-	else
-	    TIMER1=0
-	fi
-	if [ \${TIMER1} -ge 7 ]; then
-	    echo "Received 7 positive approvals, proceeding" | logger
-	    break
-	fi
-	sleep 1
-    done
 
-    if [ \${TIMER1} -lt 7 ]; then
-	echo "PANIC! Retry exhausted" | logger
-	# Just in case.  Demote ourselves.
-	ifconfig \${SUBSYSTEM} advskew 200
-	exit
+	    # This catches the case where one head is powered off but the
+	    # ethernet link shows as active due to the motherboard receiving
+	    # power.  The link speed in this case will be 10baseT and the status
+	    # will be active.  This test is not perfect because the physical
+	    # failover interface is not explicitely defined, so it would be possible
+	    # for another interface in the box to be in this state and "fake out"
+	    # the script.
+	    if [ \${STATUS1} -eq 2 -a \${STATUS2} -eq 0 ] ; then
+	        if [ \$WASCONNECTED -ne 1 ]; then
+		    for i in \`ifconfig -lu\`
+		    do
+		        ifconfig \$i | grep 10baseT/UTP
+		        if [ \$? -eq 0 ] ; then
+			    LINKSTATUS=\`ifconfig \$i | grep status | awk '{print \$2}'\`
+			    if [ \${LINKSTATUS} == "active" ] ; then
+			        WASCONNECTED=1
+			    fi
+		        fi
+	            done
+	        fi
+	        TIMER1=\$((TIMER1 + 1))
+	    else
+	        TIMER1=0
+	    fi
+	    if [ \${TIMER1} -ge 7 ]; then
+	        echo "Received 7 positive approvals, proceeding" | logger
+	        break
+	    fi
+	    sleep 1
+        done
+
+        if [ \${TIMER1} -lt 7 ]; then
+	    echo "PANIC! Retry exhausted" | logger
+	    # Just in case.  Demote ourselves.
+	    ifconfig \${SUBSYSTEM} advskew 200
+	    exit
+        fi
     fi
 
     # Bail out if this is not a warm takeover, and the heartbeat cable
     # did not give us an approval.
-    if [ \$WASCONNECTED -ne 1 ]; then
-	exit
+    if [ \${USER_OVERRIDE} -eq 0 ] ; then
+        if [ \$WASCONNECTED -ne 1 ]; then
+	    exit
+        fi
     fi
 
     ifconfig \${SUBSYSTEM} advskew 1
@@ -147,6 +160,10 @@ if [ \${EVENT} = "LINK_UP" ]; then
     echo "pass quick on \${SUBSYSTEM} keep state" > /etc/pf.conf
     pfctl -f /etc/pf.conf
     echo "\$(date), \$(hostname), assume master" | mail -s "Failover" root
+
+    if  [ -f /tmp/failover_override ] ; then
+        rm /tmp/failover_override
+    fi
 fi
 
 if [ \${EVENT} = "LINK_DOWN" ]; then
@@ -168,6 +185,7 @@ if [ \${EVENT} = "LINK_DOWN" ]; then
     echo "Exported ${volumename}!" | logger
     echo "\$(date), \$(hostname), assume backup" | mail -s "Failover" root
 fi
+
 E*O*F
 	else
 		/usr/bin/truncate -s 0 /etc/pf.conf
