Move the test of hot start case into the WASCONNECTED block. We can safely skip this part for normal case (pair was connected).

diff --git a/src/freenas/etc/rc.d/ix-devd b/src/freenas/etc/rc.d/ix-devd
--- a/src/freenas/etc/rc.d/ix-devd
+++ b/src/freenas/etc/rc.d/ix-devd
@@ -62,26 +62,6 @@ if [ \${EVENT} = "LINK_UP" ]; then
     # Test if the heartbeat cable thinks we are master
     STATUS1=\`(ifconfig carp1 | grep carp: | awk '{print \$2;}' ; ifconfig carp2 | grep carp: | awk '{print \$2;}')| grep MASTER | wc -l\`
     STATUS2=\`(ifconfig carp1 | grep carp: | awk '{print \$2;}' ; ifconfig carp2 | grep carp: | awk '{print \$2;}')| grep BACKUP | wc -l\`
-    # This catches the case where one head is powered off but the
-    # ethernet link shows as active due to the motherboard receiving
-    # power.  The link speed in this case will be 10baseT and the status
-    # will be active.  This test is not perfect because the physical
-    # failover interface is not explicitely defined, so it would be possible
-    # for another interface in the box to be in this state and "fake out"
-    # the script.
-    if [ \${STATUS1} -eq 2 -a \${STATUS2} -eq 0 ] ; then
-        for i in \`ifconfig -lu\`
-        do
-            ifconfig \$i | grep 10baseT/UTP
-            if [ \$? -eq 0 ] ; then
-                LINKSTATUS=\`ifconfig \$i | grep status | awk '{print \$2}'\`
-                if [ \${LINKSTATUS} == "active" ] ; then
-		    WASCONNECTED=1
-                fi
-            fi
-        done
-    fi
-
 
     echo \${STATUS0}:\${STATUS1}:\${STATUS2} | logger
     if [ \$STATUS0 != "MASTER" ]; then
@@ -121,7 +101,26 @@ if [ \${EVENT} = "LINK_UP" ]; then
     # Bail out if this is not a warm takeover, and the heartbeat cable
     # did not give us an approval.
     if [ \$WASCONNECTED -ne 1 ]; then
-	exit
+	# This catches the case where one head is powered off but the
+	# ethernet link shows as active due to the motherboard receiving
+	# power.  The link speed in this case will be 10baseT and the status
+	# will be active.  This test is not perfect because the physical
+	# failover interface is not explicitely defined, so it would be possible
+	# for another interface in the box to be in this state and "fake out"
+	# the script.
+	for i in \`ifconfig -lu\`
+	do
+	    ifconfig \${i} | grep 10baseT/UTP
+	    if [ \$? -eq 0 ] ; then
+		LINKSTATUS=\`ifconfig \${i} | grep status | awk '{print \$2}'\`
+		if [ \${LINKSTATUS} == "active" ] ; then
+		    WASCONNECTED=1
+		fi
+	    fi
+	done
+	if [ \$WASCONNECTED -ne 1 ]; then
+		exit
+	fi
     fi
 
     ifconfig \${SUBSYSTEM} advskew 1
