Don't forget about UFS

diff --git a/nanobsd/Files/etc/ix.rc.d/ix-system b/nanobsd/Files/etc/ix.rc.d/ix-system
--- a/nanobsd/Files/etc/ix.rc.d/ix-system
+++ b/nanobsd/Files/etc/ix.rc.d/ix-system
@@ -26,6 +26,99 @@ dataset_exists()
 	return 0
 }
 
+volume_is_zfs()
+{
+	local name="${1}"
+	local fstype
+	local res=1
+
+	fstype="$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
+		SELECT
+			vol_fstype
+		FROM
+			storage_volume
+		WHERE
+			vol_name = '${name}'
+		ORDER BY
+			-id
+		LIMIT 1
+	")"
+
+	if [ "${fstype}" = "ZFS" ]
+	then
+		res=0
+	fi
+
+	return ${res}
+}
+
+create_system_datasets_zfs()
+{
+	local system_dataset="${1}"
+	local system_datasets="${2}"
+
+	if ! dataset_exists "${system_dataset}"
+	then
+		/sbin/zfs create "${system_dataset}"
+		if ! dataset_exists "${system_dataset}"
+		then
+			echo "Unable to create ${system_dataset}"
+			exit 1
+		fi
+	fi
+
+	for ds in ${system_datasets}
+	do
+		if dataset_exists "${system_dataset}/${ds}"
+		then
+			continue
+		fi
+
+		/sbin/zfs create "${system_dataset}/${ds}"
+		if ! dataset_exists "${system_dataset}"
+		then
+			echo "Unable to create ${system_dataset}/${ds}"
+			exit 1
+		fi
+		if [ "${ds}" = "cores" ]
+		then
+			local corepath="$(zfs list -H "${system_dataset}/cores"|awk '{ print $5 }')"
+			if [ -n "${corepath}" ]
+			then
+				chmod 775 "${corepath}"
+			fi
+		fi
+	done
+}
+
+create_system_datasets_ufs()
+{
+	local system_dataset="${1}"
+	local system_datasets="${2}"
+
+	system_dataset="/mnt/${system_dataset}"
+	mkdir -p "${system_dataset}"
+	if [ "$?" != "0" ]
+	then
+		echo "Unable to create ${system_dataset}"
+		exit 1
+	fi
+
+	for ds in ${system_datasets}
+	do
+		mkdir -p "${system_dataset}/${ds}"
+		if [ "$?" != "0" ]
+		then
+			echo "Unable to create ${system_dataset}/${ds}"
+			exit 1
+		fi
+		if [ "${ds}" = "cores" ]
+		then
+			chmod 775 "${system_dataset}/cores"
+		fi
+	done
+}
+
 system_start()
 {
 	local system_datasets="samba4 syslog cores"
@@ -43,38 +136,14 @@ system_start()
 	do
 		local system_dataset="${system_pool}/.system"
 
-		if ! dataset_exists "${system_dataset}"
+		if volume_is_zfs "${system_pool}"
 		then
-			/sbin/zfs create "${system_dataset}"
-			if ! dataset_exists "${system_dataset}"
-			then
-				echo "Unable to create ${system_dataset}"
-				exit 1
-			fi
+			create_system_datasets_zfs "${system_dataset}" "${system_datasets}"
+		else
+			create_system_datasets_ufs "${system_dataset}" "${system_datasets}"
 		fi
 
-		for ds in ${system_datasets}
-		do
-			if dataset_exists "${system_dataset}/${ds}"
-			then
-				continue
-			fi
-
-			/sbin/zfs create "${system_dataset}/${ds}"
-			if ! dataset_exists "${system_dataset}"
-			then
-				echo "Unable to create ${system_dataset}/${ds}"
-				exit 1
-			fi
-			if [ "${ds}" = "cores" ]
-			then
-				local corepath="$(zfs list -H "${system_dataset}/cores"|awk '{ print $5 }')"
-				if [ -n "${corepath}" ]
-				then
-					chmod 775 "${corepath}"
-				fi
-			fi
-		done
+		sysctl kern.corefile="/mnt/${system_dataset}/cores/%N.core" >/dev/null
 	done
 
 	return 0
