Fix builds with only svn installed on the box. Sometimes nano_env is executed with set -e, so if git or svn isn't present, the build would fail.
This addresses ticket 1006.

diff --git a/build/nano_env b/build/nano_env
--- a/build/nano_env
+++ b/build/nano_env
@@ -31,8 +31,10 @@ NANO_SRC="$FREENAS_ROOT/FreeBSD/src"
 NANO_TOOLS="$FREENAS_ROOT/build/nanobsd"
 
 if [ -z "${SVNVERSION}" ]; then
-	svnversion=$(command -v svnversion)
-	git_cmd=$(command -v git)
+	# This is executed sometimes as set -e; don't let it fail by no-oping
+	# it.
+	svnversion=$(command -v svnversion || :)
+	git_cmd=$(command -v git || :)
 
 	if [ -n "$svnversion" ] ; then
 		# svn prints out errors to stdout. Bad svn! No cookie for you!
