Merge r8623:8824 from trunk into the CLI branch.

diff --git a/build/nano_env b/build/nano_env
--- a/build/nano_env
+++ b/build/nano_env
@@ -30,16 +30,52 @@ NANO_SRC="$FREENAS_ROOT/FreeBSD/src"
 # Where the nanobsd tools live.
 NANO_TOOLS="$FREENAS_ROOT/build/nanobsd"
 
+if [ -z "${SVNVERSION}" ]; then
+	# This is executed sometimes as set -e; don't let it fail by no-oping
+	# it.
+	svnversion=$(command -v svnversion || :)
+	git_cmd=$(command -v git || :)
+
+	if [ -n "$svnversion" ] ; then
+		# svn prints out errors to stdout. Bad svn! No cookie for you!
+		svn="r`cd ${FREENAS_ROOT} && /usr/bin/env LANG=C $svnversion; cd -`" || svn=""
+	fi
+	[ "${svn}" = "rUnversioned directory" ] && svn=""
+	if [ -z "$svn" ]; then
+		if [ -n "$git_cmd" ] ; then
+			git=`$git_cmd rev-parse --verify --short HEAD 2>/dev/null`
+			svn=`$git_cmd svn find-rev $git 2>/dev/null`
+			if [ -n "$svn" ] ; then
+				svn="r${svn}"
+				git="=${git}"
+			else
+				svn=`$git_cmd log | fgrep 'git-svn-id:' | head -1 | \
+				    sed -n 's/^.*@\([0-9][0-9]*\).*$/\1/p'`
+				if [ -n $svn ] ; then
+					svn="r${svn}"
+					git="+${git}"
+				else
+					git="${git}"
+				fi
+			fi
+			if $git_cmd --work-tree=${FREENAS_ROOT} diff-index \
+			    --name-only HEAD | read dummy; then
+				git="${git}-dirty"
+			fi
+		fi
+	fi
+fi
+
 # REVISION gets overloaded when doing tagged versions, SVNREVISION allows
 # us to keep the SVN revision number even when the version string is
 # overloaded with a name.
-: ${SVNREVISION=r$(svnversion ${NANO_CFG_BASE})}
-: ${REVISION=r$(svnversion ${NANO_CFG_BASE})}
+SVNREVISION=${SVNREVISION:-$(echo ${svn}${git})}
+REVISION=${REVISION:-$(echo ${svn}${git})}
 
 NANO_KERNEL="$NANO_CFG_BASE/FREENAS.$NANO_ARCH"
 
 # Modules to build with the kernel.
-NANO_MODULES="cxgb ext2fs geom ntfs smbfs libiconv libmchain pf pflog udf zfs opensolaris usb/xhci"
+NANO_MODULES="cxgb ext2fs geom ipmi ntfs pf pflog smbfs libiconv libmchain syscons udf zfs opensolaris usb/xhci"
 
 # Feature sets to enable as part of the build.
 SW_FEATURES="DEBUG REPORTING"
@@ -50,10 +86,9 @@ NANO_LABEL="FreeNAS"
 # Version of the software.
 VERSION="8.2"
 
-# Image prefix, e.g. FreeNAS-8.1-r7609-amd64 or FreeNAS-8.0.1-RC1-i386.
+# Image name, e.g. FreeNAS-8.1-r7609-amd64 or FreeNAS-8.0.1-RC1-i386, see
+# nanobsd/freenas-common:last_orders().
 NANO_NAME="$NANO_LABEL-$VERSION-$REVISION-$NANO_ARCH"
-
-# Image with a suffix
 NANO_IMGNAME="$NANO_NAME"
 
 # Export these vars to override the NanoBSD defaults.
