DTRT when switching between AD and LDAP
sef agreed with me that I shouldn't be clever.

Ticket: #12939

When we switch between AD and LDAP, or move around the AD homedir
path we don't do the proper amount of cleanup.  The left over
home directory symlinks from AD give the LDAP scripts heartburn
and vice-versa.

Consider this commit the equivilent to giving FreeNAS a Rolaids.
It's not very clever, and I added some comments that describe
how we uncleverly smash rocks together and why we are smashing the
rocks together in the precise way that we are.
(Rock smashing is a tiring business, and if you aren't careful
you can get rock slivers in your eye, so it pays to have some
guidance before blindly smashing rocks together.)

There's a dearth of comments in the LDAP code.  The few I sprinkled
in aren't really much help to someone trying to understand how this
all works.

(cherry picked from commit a60eef59ef5e77a7c3bc9e3b70cbdb8996cd95c4)

diff --git a/src/freenas/etc/ix.rc.d/ix-ldap b/src/freenas/etc/ix.rc.d/ix-ldap
--- a/src/freenas/etc/ix.rc.d/ix-ldap
+++ b/src/freenas/etc/ix.rc.d/ix-ldap
@@ -40,15 +40,47 @@ get_cifs_homedir()
 
 setup_homedirs()
 {
+	# Stale symlinks and directories can make us sad.  This can happen
+	# when you update the homedir path, or switch between LDAP and AD.
+
 	local cifs_home="$(get_cifs_homedir)"
 
-	if [ -n "${cifs_home}" ]
-	then
+	# if /home is a dead symlink nuke it
+	find /home -type l -maxdepth 0 -exec test ! -e {} \; -exec rm '{}' \;
+
+	if [ -n "${cifs_home}" ] ; then
+		# If /home is a directory nuke it
+		if [ -d "/home" ]; then
+			rmdir /home 2>/dev/null
+			if  [ $? -ne 0 ]; then
+				# rmdir has failed us, the directory must not be empty
+				# In theory this should never happen, so we won't worry
+				# about name collisions in our random new name.
+				newhome="/home.$(dd if=/dev/random bs=4 count=1 2>/dev/null | base64 | sed -e 's/[\/|=]//g')"
+				mv /home ${newhome}
+			fi
+		fi
+		# It's safe to create/update our symlink now
 		ln -sfh "$cifs_home" "/home" 2>/dev/null
 
-	elif [ ! -d "/home" ]
-	then
-		mkdir /home
+	else
+		if [ -e "/home" ]; then
+			if [ -d "/home" ]; then
+				# Nothing to do here
+			else
+				# The only possibility here is /home is a file
+				# or a valid symlink
+				rm /home
+				mkdir /home
+			fi
+		else
+			# In theory this shouldn't be possible.  Dead symlinks get nuked
+			# and working symlinks wouldn't get to this else clause
+			if [ -L "/home" ]; then
+				rm /home
+			fi
+			mkdir /home
+		fi
 	fi
 }
 
