fix(netif): fallback to rc.d network if the call fails
Suggested by @themylogin

Ticket:	#35769

diff --git a/src/freenas/etc/ix.rc.d/ix-netif b/src/freenas/etc/ix.rc.d/ix-netif
--- a/src/freenas/etc/ix.rc.d/ix-netif
+++ b/src/freenas/etc/ix.rc.d/ix-netif
@@ -11,12 +11,10 @@
 netif_start()
 {
 	echo "Starting interfaces..."
-	/usr/local/bin/midclt -t 120 call interfaces.sync true > /dev/null
-
-	# If middlewared failed to start for some reason we need to fallback
-	# to configuring interfaces using rc.d/netif for debugging.
+	# If middlewared failed to start for some reason or the call failed
+	# we need to fallback to configuring interfaces using rc.d/netif for debugging.
 	# Sentinel file checked in rc.conf.local
-	if ! /usr/local/bin/midclt call core.ping > /dev/null 2>&1; then
+	if ! /usr/local/bin/midclt -t 120 call interfaces.sync true > /dev/null 2>&1; then
 		touch ${FREENAS_MW_IFACES_FAILED}
 		# Removing file makes sure rc.conf cache is regenerated on next rc.d call
 		rm -rf ${FREENAS_CONFIG_MD5}
