First checkin of major changes for installation.
Incomplete, but this includes changes to both the build
and install process, and various scripts and modules
to support that.

This still doesn't boot multi-user.  Or handle upgrades.

diff --git a/src/freenas/etc/ix.rc.d/ix-update b/src/freenas/etc/ix.rc.d/ix-update
--- a/src/freenas/etc/ix.rc.d/ix-update
+++ b/src/freenas/etc/ix.rc.d/ix-update
@@ -40,11 +40,11 @@ Database upgrade FAILED; check $UPDATE_FAILED_LOG for more details.
 Reverting a failed CD upgrade is not totally possible
 Rebooting in 15 seconds..
 EOF
-		umount /data
+#		umount /data
 		sleep 15
 		reboot
 	fi
-	umount /data
+#	umount /data
 
 	. /etc/nanobsd.conf
 
@@ -69,21 +69,21 @@ EOF
 
 db_update()
 {
-	if ! fsck -p /data; then
-		echo "/data couldn't be preened clean; trying full fsck"
-		if ! fsck -y /data; then
-			echo "Cannot fsck -y /data either; your system is probably hosed :(."
-			exit 1
-		fi
-	fi
-	if ! mount -w -onoatime /data; then
-		echo "Cannot mount /data to see if you need an upgrade."
-		exit 1
-	fi
+#	if ! fsck -p /data; then
+#		echo "/data couldn't be preened clean; trying full fsck"
+#		if ! fsck -y /data; then
+#			echo "Cannot fsck -y /data either; your system is probably hosed :(."
+#			exit 1
+#		fi
+#	fi
+#	if ! mount -w -onoatime /data; then
+#		echo "Cannot mount /data to see if you need an upgrade."
+#		exit 1
+#	fi
 	if [ ! -f $NEED_UPDATE_SENTINEL ]; then
 		# XXX: this seems somewhat dangerous, depending on script
 		# ordering and system state.
-		umount /data 
+#		umount /data 
 		# No need to update, exit script and continue boot
 		exit 0
 	fi
@@ -105,7 +105,7 @@ db_update()
 
 
 	# Things that just need to read from /data can follow this.
-	mount -ur /data
+#	mount -ur /data
 
 	# NOTE: this must be run via the rc.d script, not service(8).
 	env AUTOTUNE_REBOOT=false /etc/ix.rc.d/ix-loader start
