Revert r12708

diff --git a/nanobsd/Files/etc/rc.d/ix-nginx b/nanobsd/Files/etc/rc.d/ix-nginx
--- a/nanobsd/Files/etc/rc.d/ix-nginx
+++ b/nanobsd/Files/etc/rc.d/ix-nginx
@@ -11,6 +11,103 @@
 
 NGINX_PLUGINS_CONF="${HTTPDDIR}/plugins.conf"
 NGINX_FASTCGI_PARAMS="${HTTPDDIR}/fastcgi_params"
+NGINX_BACKUP_CONF="${HTTPDCONF}.working"
+
+
+backup_nginx_conf()
+{
+	if [ -f "${HTTPDCONF}" ]
+	then
+		cp "${HTTPDCONF}" "${NGINX_BACKUP_CONF}"
+		return $?
+	fi
+
+	return 1
+}
+
+
+restore_nginx_conf()
+{
+	if [ -f "${NGINX_BACKUP_CONF}" ]
+	then
+		mv "${NGINX_BACKUP_CONF}" "${HTTPDCONF}"
+		return $?
+	fi
+
+	return 1
+}
+
+
+nginx_cmd()
+{
+	local cmd="${1}" 
+
+	${HTTPDSCRIPT} "${cmd}" >/dev/null 2>&1
+	if [ "$?" = "0" ]
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+
+nginx_start()
+{
+	local st="${1}"
+
+	nginx_cmd "start"
+	if [ "$?" = "0" ]
+	then
+		nginx_cmd "status"
+		if [ "$?" = "0" ]
+		then
+			if [ -n "${st}" ]
+			then
+				sleep "${st}" >/dev/null 2>&1
+			fi
+			return 0
+		fi
+	fi
+
+	return 1
+}
+
+
+nginx_reload()
+{
+	local st="${1}"
+
+	nginx_cmd "reload"
+	if [ "$?" = "0" ]
+	then
+		nginx_cmd "status"
+		if [ "$?" = "0" ]
+		then
+			if [ -n "${st}" ]
+			then
+				sleep "${st}" >/dev/null 2>&1
+			fi
+			return 0
+		fi
+	fi
+
+	return 1
+}
+
+
+nginx_stop()
+{
+	nginx_cmd "stop"
+	return $?
+}
+
+
+nginx_status()
+{
+	nginx_cmd "status"
+	return $?
+}
 
 
 generate_plugins_conf()
@@ -236,6 +333,49 @@ get_host_ip()
 }
 
 
+test_nginx_conf()
+{
+	local proto="${1}"
+	local addr="${2}"
+	local port="${3}"
+	local ntries=5
+	local res=1
+	local try=0
+	local rc=1
+	
+	local host=$(get_host_ip "${addr}")
+	if [ -n "${port}" ]
+	then
+		host="${host}:${port}"
+	fi
+
+	export HTTP_TIMEOUT=1
+	export FTP_TIMEOUT=1
+
+	echo -n "Waiting for ${proto}... "
+	while [ "${try}" -lt "${ntries}" ]
+	do
+		fetch -q -o /dev/null "${proto}://${host}" >/dev/null 2>&1
+		if [ "$?" = "0" ]
+		then
+			rc=0
+			break		
+		fi
+
+		: $(( try += 1 ))
+		sleep 1
+	done
+	if [ "${rc}" = "0" ]
+	then
+		echo "Done."
+	else
+		echo "Failed."
+	fi
+
+	return $rc
+}
+
+
 set_stg_guiprotocol()
 {
 	local res=1
@@ -363,6 +503,59 @@ get_nginx_settings()
 }
 
 
+verify_nginx_conf()
+{
+	${HTTPD} -t -q -c "${HTTPDCONF}" >/dev/null 2>&1
+	if [ "$?" != "0" ]
+	then
+		return 1
+	fi
+
+	return 0
+}
+
+
+ix_nginx_reload()
+{
+	local settings=$(get_nginx_settings)
+
+	local proto=$(echo "${settings}"|cut -f1 -d:)
+	local addr=$(echo "${settings}"|cut -f2 -d:)
+	local port=$(echo "${settings}"|cut -f3 -d:)
+
+	if [ "${proto}" = "https" -a ! -f "${SSLCONF}" ]
+	then
+		port="80"
+		proto="http"
+
+		set_stg_guiprotocol "${proto}"
+		set_stg_guiport "${port}"
+	fi
+
+	generate_plugins_conf
+	generate_fastcgi_params
+
+	backup_nginx_conf
+	generate_nginx_conf "${proto}" "${addr}" "${port}"
+
+	if ! test_nginx_conf "${proto}" "${addr}" "${port}"
+	then
+		restore_nginx_conf
+		nginx_reload
+		return 1
+	fi
+
+	if ! nginx_reload
+	then
+		restore_nginx_conf
+		nginx_reload
+		return 1
+	fi
+
+	return 0
+}
+
+
 ix_nginx_start()
 {
 	local settings=$(get_nginx_settings)
@@ -383,13 +576,38 @@ ix_nginx_start()
 	generate_plugins_conf
 	generate_fastcgi_params
 
+	backup_nginx_conf
 	generate_nginx_conf "${proto}" "${addr}" "${port}"
 
+	if nginx_status
+	then
+		nginx_reload 5
+	else
+		nginx_start 5
+	fi
+	
+	if [ "$?" != "0" ]
+	then
+		restore_nginx_conf
+		nginx_stop
+		return 1
+	fi
+
+	if ! test_nginx_conf "${proto}" "${addr}" "${port}"
+	then
+		restore_nginx_conf
+		nginx_stop
+		return 1
+	fi
+
+	nginx_stop
+	return 0
 }
 
 
 name="ix-nginx"
 start_cmd='ix_nginx_start'
+reload_cmd='ix_nginx_reload'
 stop_cmd=':'
             
 extra_commands="reload"
