Hand merge changes from trunk to 8.0.4. ------------------------------------------------------------------------ r9069 | yaberauneya | 2011-12-10 16:06:04 -0800 (Sat, 10 Dec 2011) | 2 lines
Reap the declaration for a now unused var.

------------------------------------------------------------------------
r9051 | zippybr | 2011-12-09 07:58:08 -0800 (Fri, 09 Dec 2011) | 2 lines

i think we should be redirecting stderr as well for /data/update.failed
that is the reason this file is always empty on migration fails
------------------------------------------------------------------------
r9049 | zippybr | 2011-12-09 03:48:52 -0800 (Fri, 09 Dec 2011) | 3 lines

AFAIK there is no reason at all to run migrations indepedently,
even because some of them have dependency anyway.
I'm removing this hack unless someone has a good reason for it to stay.
------------------------------------------------------------------------
r9043 | yaberauneya | 2011-12-09 01:25:33 -0800 (Fri, 09 Dec 2011) | 8 lines

Fix migrations, from pre-plugins to post-plugins.

Now migrations are obtained dynamically by looking at the 0001*.py files and deriving the migration 'category' names from there.

This mutes plugins_plugins missing tables noise at boot and fixes display the tree menu on trunk after doing a CD or GUI upgrade.

This addresses the rest of ticket 1072.
------------------------------------------------------------------------
r8666 | yaberauneya | 2011-11-14 13:57:41 -0800 (Mon, 14 Nov 2011) | 7 lines

Merge changes from ix to sf-trunk
------------------------------------------------------------------------
r4051 | gcooper | 2011-11-14 13:04:05 -0800 (Mon, 14 Nov 2011) | 2 lines

Fix inverted logic.

diff --git a/nanobsd/Files/etc/rc.d/ix-update b/nanobsd/Files/etc/rc.d/ix-update
--- a/nanobsd/Files/etc/rc.d/ix-update
+++ b/nanobsd/Files/etc/rc.d/ix-update
@@ -12,20 +12,16 @@ readonly UPDATE_FAILED_LOG="/data/update.failed"
 
 db_update_real()
 {
-	local i
-
 	echo "Applying database schema changes"
 
-	for i in account freeadmin network services sharing storage system; do
-		yes | /usr/local/bin/python \
-		    /usr/local/www/freenasUI/manage.py migrate --merge $i > \
-		    $UPDATE_FAILED_LOG
-		if [ $? -ne 0 ]; then
-			echo "manage.py migrate $i failed"
-			return 1
-		fi
-	done
-	rm -f $UPDATE_FAILED_LOG 
+	yes | /usr/local/bin/python \
+	    /usr/local/www/freenasUI/manage.py migrate --merge > \
+		$UPDATE_FAILED_LOG 2>&1
+	if [ $? -ne 0 ]; then
+		echo "manage.py migrate failed"
+		return 1
+	fi
+	rm -f $UPDATE_FAILED_LOG
 	return 0
 }
 
@@ -52,11 +48,11 @@ EOF
 
 	LABELNAME=`echo ${NANO_DRIVE} | cut -f2 -d/`
 	if mount | grep ${NANO_DRIVE}s1 > /dev/null ; then
-		PARTNUM=2
-		OTHER_PARTNUM=1
-	else
 		PARTNUM=1
 		OTHER_PARTNUM=2
+	else
+		PARTNUM=2
+		OTHER_PARTNUM=1
 	fi
 	TARGET_DRIVE=`glabel status | awk '/ufs\/'${LABELNAME}s${PARTNUM}'a/ { print $3; }' | sed -e 's/s.a//'`
 	gpart set -a active -i $OTHER_PARTNUM ${TARGET_DRIVE}
