Merge r8826:r10238

diff --git a/nanobsd/Files/etc/rc.d/ix-update b/nanobsd/Files/etc/rc.d/ix-update
--- a/nanobsd/Files/etc/rc.d/ix-update
+++ b/nanobsd/Files/etc/rc.d/ix-update
@@ -6,26 +6,22 @@
 # PROVIDE: ix-update
 # BEFORE: ix-fstab
 
-. /etc/rc.subr
+. /etc/rc.freenas
 
 readonly UPDATE_FAILED_LOG="/data/update.failed"
 
 db_update_real()
 {
-	local i
-
 	echo "Applying database schema changes"
 
-	for i in account freeadmin network services sharing storage system; do
-		yes | /usr/local/bin/python \
-		    /usr/local/www/freenasUI/manage.py migrate --merge $i > \
-		    $UPDATE_FAILED_LOG
-		if [ $? -ne 0 ]; then
-			echo "manage.py migrate $i failed"
-			return 1
-		fi
-	done
-	rm -f $UPDATE_FAILED_LOG 
+	yes | /usr/local/bin/python \
+	    /usr/local/www/freenasUI/manage.py migrate --merge > \
+		$UPDATE_FAILED_LOG 2>&1
+	if [ $? -ne 0 ]; then
+		echo "manage.py migrate failed"
+		return 1
+	fi
+	rm -f $UPDATE_FAILED_LOG
 	return 0
 }
 
@@ -35,18 +31,20 @@ handle_error()
 
 	echo "Reverting to previous state"
 
-	rm -f /data/need-update
+	rm -f $NEED_UPDATE_SENTINEL
 	mv ${FREENAS_CONFIG}.bak ${FREENAS_CONFIG}
-	if [ -f /data/cd_upgrade ]; then
-		rm /data/cd_upgrade
+	if [ -f $CD_UPGRADE_SENTINEL ]; then
+		rm $CD_UPGRADE_SENTINEL
 		cat <<EOF
 Database upgrade FAILED; check $UPDATE_FAILED_LOG for more details.
 Reverting a failed CD upgrade is not totally possible
 Rebooting in 15 seconds..
 EOF
+		umount /data
 		sleep 15
 		reboot
 	fi
+	umount /data
 
 	. /etc/nanobsd.conf
 
@@ -78,11 +76,11 @@ db_update()
 			exit 1
 		fi
 	fi
-	if ! mount -w /data; then
+	if ! mount -w -onoatime /data; then
 		echo "Cannot mount /data to see if you need an upgrade."
 		exit 1
 	fi
-	if [ ! -f /data/need-update ]; then
+	if [ ! -f $NEED_UPDATE_SENTINEL ]; then
 		# XXX: this seems somewhat dangerous, depending on script
 		# ordering and system state.
 		umount /data 
@@ -100,11 +98,18 @@ db_update()
 	db_update_real || handle_error
 	set -e
 
-	rm -f /data/need-update
-	if [ -f /data/cd_upgrade ]; then
-		rm /data/cd_upgrade
-	fi
-	umount /data
+	rm -f $NEED_UPDATE_SENTINEL
+	rm -f $CD_UPGRADE_SENTINEL
+
+	# Things that need write access to /data can follow this.
+
+
+	# Things that just need to read from /data can follow this.
+	mount -ur /data
+
+	# NOTE: this must be run via the rc.d script, not service(8).
+	env AUTOTUNE_REBOOT=false /etc/rc.d/ix-loader start
+
 	echo "Database upgrade complete.  Rebooting."
 	cd /
 	sleep 2
diff --git a/nanobsd/common b/nanobsd/common
--- a/nanobsd/common
+++ b/nanobsd/common
@@ -64,7 +64,7 @@ clean_packages()
 	for f in bin etc lib libdata libexec sbin share; do
 		mkdir -p ${LOCAL_DIR}/$f
 	done
-	find /var/db/pkg/ -mindepth 1 -maxdepth 1 | xargs rm -Rf
+	find ${LOCAL_DIR}/var/db/pkg/ -mindepth 1 -maxdepth 1 | xargs rm -Rf
 }
 customize_cmd clean_packages
 
@@ -80,7 +80,11 @@ customize_cmd cust_install_machine_files
 buildenv()
 {
 	cd ${NANO_SRC}
-	env __MAKE_CONF=${NANO_MAKE_CONF_BUILD} DESTDIR=${NANO_WORLDDIR} make buildenv
+	env \
+		DESTDIR=${NANO_WORLDDIR} \
+		${NANO_PMAKE} \
+		buildenv \
+		__MAKE_CONF=${NANO_MAKE_CONF_BUILD}
 }
 
 NANO_MAKEFS="makefs -B big \
@@ -141,10 +145,13 @@ WITHOUT_SENDMAIL=true
 WITHOUT_SSP=true
 WITHOUT_SYSCONS=true
 WITHOUT_SYSINSTALL=true
-WITHOUT_TELNET=true
+# Telnet's a useful tool to have on the remote box.
+#WITHOUT_TELNET=true
 WITHOUT_WIRELESS=true
 WITHOUT_WPA_SUPPLICANT_EAPOL=true
 PYTHON_DEFAULT_VERSION=python2.7
+
+LOCAL_DIRS=${NANO_LOCAL_DIRS}
 
 ${DEBUG_BUILD}
 "
@@ -172,6 +179,11 @@ WITHOUT_SHAREDOCS=true
 "
 
 NANO_PACKAGE_ONLY=1
+
+# Ports compiles need to be free of locale tainting.
+for v in $(env | egrep '^(LANG|LC).*='); do
+	unset ${v%=*}
+done
 
 CR()
 {
@@ -243,7 +255,8 @@ do_add_port ()
 # Improvement: Don't know why package-recursive don't works here
 	CR "env \
 	    TARGET=${NANO_ARCH} \
-	    TARGET_ARCH=${NANO_ARCH} make \
+	    TARGET_ARCH=${NANO_ARCH} \
+	    make \
 	    __MAKE_CONF=${NANO_MAKE_CONF_BUILD} \
 	    SRC_BASE=/usr/src \
 	    WRKDIRPREFIX=/usr/workdir -C /usr/ports/$port_path \
@@ -262,6 +275,7 @@ do_add_port ()
 # Recursive complex function: Generate one function for each ports
 add_port ()
 {
+    local _add_pkg
     local port_path=$1
     local port=`echo $1 | sed -e 's/\//_/'`
     shift
@@ -271,9 +285,26 @@ add_port ()
     # 2. Add a trap
     cd ${NANO_PORTS}/${port_path}
     # __MAKE_CONF -> ${NANO_MAKE_CONF_BUILD} -- can't plug this in because of a sourcing chicken and egg problem.
+    set +e
     PKG_NAME=`make ${PKGNAME_HACK} PORTSDIR=${NANO_PORTS} __MAKE_CONF=${NANO_OBJ}/make.conf.install OPTIONSFILE=/nonexistent package-name $*`
-    if [ -f ${NANO_OBJ}/ports/packages/All/${PKG_NAME}.tbz ]; then
+    if [ $? -ne 0 ]; then
+        echo "failed to determine the package name for $port_path"
+        exit 1
+    fi
+    set -e
+
+    _add_pkg=false
+    if $do_world && $do_clean; then
+        # HACK: make do_build.sh -ff work properly instead of having
+        # do_add_pkg fall flat on its face when it tries to add the
+        # missing package.
+        :
+    elif [ -f ${NANO_OBJ}/ports/packages/All/${PKG_NAME}.tbz ]; then
 	# Pkg file found: Generate add_pkg_NAME function
+        _add_pkg=true
+    fi
+
+    if $_add_pkg; then
 	eval "
 	    add_pkg_${port} () {
 	        do_add_pkg ${PKG_NAME}
@@ -281,7 +312,6 @@ add_port ()
             customize_cmd add_pkg_${port}
             "
     else
-	# No pkg file: Generate add_port_NAME function
 	echo "Package is not yet built: $port"
         eval "
             add_port_${port} () {
