Attempt to make the update procedure more robust and supportable.

diff --git a/nanobsd/Files/etc/rc.d/ix-update b/nanobsd/Files/etc/rc.d/ix-update
--- a/nanobsd/Files/etc/rc.d/ix-update
+++ b/nanobsd/Files/etc/rc.d/ix-update
@@ -8,6 +8,69 @@
 
 . /etc/rc.subr
 
+db_update_real()
+{
+	echo "Applying database schema changes"
+
+	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate account > /data/upgrade.failed
+	if [ "$?" != "0" ]; then
+		echo "manage.py migrate account failed"
+		return 1
+	fi
+	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate freeadmin > /data/upgrade.failed
+	if [ "$?" != "0" ]; then
+		echo "manage.py migrate freeadmin failed"
+		return 1
+	fi
+	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate network > /data/upgrade.failed
+	if [ "$?" != "0" ]; then
+		echo "manage.py migrate network failed"
+		return 1
+	fi
+	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate services > /data/upgrade.failed
+	if [ "$?" != "0" ]; then
+		echo "manage.py migrate services failed"
+		return 1
+	fi
+	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate sharing > /data/upgrade.failed
+	if [ "$?" != "0" ]; then
+		echo "manage.py migrate sharing failed"
+		return 1
+	fi
+	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate storage > /data/upgrade.failed
+	if [ "$?" != "0" ]; then
+		echo "manage.py migrate storage failed"
+		return 1
+	fi
+	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate system > /data/upgrade.failed
+	if [ "$?" != "0" ]; then
+		echo "manage.py migrate system failed"
+		return 1
+	fi
+	rm /data/upgrade.failed
+	return 0
+}
+
+handle_error()
+{
+	echo "Reverting to previous state"
+
+	rm -f /data/need-update
+	mv ${FREENAS_CONFIG}.bak ${FREENAS_CONFIG}
+
+	. /etc/nanobsd.conf
+
+	if mount | grep ${NANO_DRIVE}s1 > /dev/null ; then
+		gpart set -a active -i 2 ${TARGET_DRIVE}
+	else
+		gpart set -a active -i 1 ${TARGET_DRIVE}
+	fi
+
+	echo "Database upgrade FAILED, check /data/upgrade.failed.  Rebooting in 15 seconds."
+	sleep 15
+	reboot
+}
+
 db_update()
 {
 	if ! fsck -p /data; then
@@ -29,87 +92,11 @@ db_update()
 	fi
 	echo "Saving current ${FREENAS_CONFIG} to ${FREENAS_CONFIG}.bak"
 	cp ${FREENAS_CONFIG} ${FREENAS_CONFIG}.bak
-	echo "Updating database"
-	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} .schema | grep south_migrationhistory > /dev/null
-	if [ "$?" != "0" ]; then
-		echo "Converting pre-south database"
-		/usr/local/bin/python /usr/local/www/freenasUI/manage.py syncdb > /dev/null
-		if [ "$?" != "0" ]; then
-			echo "manage.py syncdb failed"
-			exit
-		fi
-		/usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate account 0001 --fake > /dev/null
-		if [ "$?" != "0" ]; then
-			echo "manage.py migrate account 0001 --fake failed"
-			exit
-		fi
-		/usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate freeadmin 0001 --fake > /dev/null
-		if [ "$?" != "0" ]; then
-			echo "manage.py migrate freeadmin 0001 --fake failed"
-			exit
-		fi
-		/usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate network 0001 --fake > /dev/null
-		if [ "$?" != "0" ]; then
-			echo "manage.py migrate network 0001 --fake failed"
-			exit
-		fi
-		/usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate services 0001 --fake > /dev/null
-		if [ "$?" != "0" ]; then
-			echo "manage.py migrate services 0001 --fake failed"
-			exit
-		fi
-		/usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate sharing 0001 --fake > /dev/null
-		if [ "$?" != "0" ]; then
-			echo "manage.py migrate sharing 0001 --fake failed"
-			exit
-		fi
-		/usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate storage 0001 --fake > /dev/null
-		if [ "$?" != "0" ]; then
-			echo "manage.py migrate storage 0001 --fake failed"
-			exit
-		fi
-		/usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate system 0001 --fake > /dev/null
-		if [ "$?" != "0" ]; then
-			echo "manage.py migrate system 0001 --fake failed"
-			exit
-		fi
-	fi
-	echo "Applying database schema changes"
-	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate account > /dev/null
-	if [ "$?" != "0" ]; then
-		echo "manage.py migrate account failed"
-		exit
-	fi
-	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate freeadmin > /dev/null
-	if [ "$?" != "0" ]; then
-		echo "manage.py migrate freeadmin failed"
-		exit
-	fi
-	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate network > /dev/null
-	if [ "$?" != "0" ]; then
-		echo "manage.py migrate network failed"
-		exit
-	fi
-	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate services > /dev/null
-	if [ "$?" != "0" ]; then
-		echo "manage.py migrate services failed"
-		exit
-	fi
-	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate sharing > /dev/null
-	if [ "$?" != "0" ]; then
-		echo "manage.py migrate sharing failed"
-		exit
-	fi
-	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate storage > /dev/null
-	if [ "$?" != "0" ]; then
-		echo "manage.py migrate storage failed"
-		exit
-	fi
-	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate system > /dev/null
-	if [ "$?" != "0" ]; then
-		echo "manage.py migrate system failed"
-		exit
-	fi
+
+	set +e
+	db_update_real || handle_error
+	set -e
+
 	rm -f /data/need-update
 	umount /data
 	echo "Database upgrade complete.  Rebooting."
