Add migrations to account app, fix template error

diff --git a/nanobsd/Files/etc/rc.d/ix-update b/nanobsd/Files/etc/rc.d/ix-update
--- a/nanobsd/Files/etc/rc.d/ix-update
+++ b/nanobsd/Files/etc/rc.d/ix-update
@@ -38,6 +38,11 @@ db_update()
 			echo "manage.py syncdb failed"
 			exit
 		fi
+		/usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate account 0001 --fake > /dev/null
+		if [ "$?" != "0" ]; then
+			echo "manage.py migrate account 0001 --fake failed"
+			exit
+		fi
 		/usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate network 0001 --fake > /dev/null
 		if [ "$?" != "0" ]; then
 			echo "manage.py migrate network 0001 --fake failed"
@@ -65,6 +70,11 @@ db_update()
 		fi
 	fi
 	echo "Applying database schema changes"
+	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate account > /dev/null
+	if [ "$?" != "0" ]; then
+		echo "manage.py migrate account failed"
+		exit
+	fi
 	yes | /usr/local/bin/python /usr/local/www/freenasUI/manage.py migrate network > /dev/null
 	if [ "$?" != "0" ]; then
 		echo "manage.py migrate network failed"
